import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR, { mutate } from "swr";

// fetcher function to enable use of SWR callback
const fetcher = async (url) => {
  const res = await fetch(url);
  const data = await res.json();
  if (res.status !== 200) {
    throw new Error(data.message);
  }

  return data;
};

export default function Home() {
  const { data, error } = useSWR("/api/snowflake", fetcher);
  if (error) return <div>{error.message}</div>;
  if (!data) return <div>Loading...</div>;

  if (data.data.data.unsplash_Search.results[0].urls.full === null) {
    return <div>null response</div>;
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Generate a Random Snowflake</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Generate a random image of a snowflake &rarr;</h2>
              <Image
                src={data.data.data.unsplash_Search.results[0].urls.full}
                alt="snowflake"
                width="100%"
                height="100%"
              />
              <div>
                <button
                  className={styles.button}
                  onClick={() => {
                    mutate("/api/snowflake");
                  }}
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    );
  }
}
